##
## Makefile for Arcade in /home/dupard_e/rendus/cpp_arcade/lib
## 
## Made by Erwan Dupard
## Login   <dupard_e@epitech.net>
## 
## Started on  Wed Mar  9 18:28:49 2016 Erwan Dupard
## Last update Thu Mar 31 14:44:13 2016 Barthelemy Gouby
##

all:
	make -C ./arcade_caca/
	make -C ./arcade_lapin/
	make -C ./arcade_sdl2/
	make -C ./arcade_pacman/
	make -C ./arcade_snake/

clean:
	make -C ./arcade_caca clean
	make -C ./arcade_lapin clean
	make -C ./arcade_sdl2 clean
	make -C ./arcade_pacman clean
	make -C ./arcade_snake clean

fclean:
	make -C ./arcade_caca fclean
	make -C ./arcade_lapin fclean
	make -C ./arcade_sdl2 fclean
	make -C ./arcade_pacman fclean
	make -C ./arcade_snake fclean

re:
	make -C ./arcade_caca re
	make -C ./arcade_lapin re
	make -C ./arcade_sdl2 re
	make -C ./arcade_pacman re
	make -C ./arcade_snake re
